{
 "title": "Air Quality Data",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Particulate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT env_pm10, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, env_pm10, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT env_pm10, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, env_pm10, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT env_pm25, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, env_pm25, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT env_pm25, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, env_pm25, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT env_pm100, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, env_pm100, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT env_pm100, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, env_pm100, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT data_pres_bme, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_pres_bme, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT data_pres_bme, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_pres_bme, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Carbon Monoxide (PPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT co_value, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, co_value, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT co_value, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, co_value, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT data_hum_bme, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_hum_bme, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT data_hum_bme, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_hum_bme, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Methane (PPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT gas_value, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, gas_value, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT gas_value, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, gas_value, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CO2 (PPM)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT data_CO2, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_CO2, datetime as \"time\" FROM converted ORDER BY datetime ASC\n",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT data_CO2, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_CO2, datetime as \"time\" FROM converted ORDER BY datetime ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT data_gas_bme, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_gas_bme, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT data_gas_bme, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_gas_bme, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "queryText": "WITH CONVERTED AS ( \n   SELECT data_temp_bme, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_temp_bme, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "rawQueryText": "WITH CONVERTED AS ( \n   SELECT data_temp_bme, STRFTIME('%Y-%m-%dT%H:%M:%SZ', date) AS datetime, 1000*STRFTIME('%Y-%m-%d %H:%M:%S', date) AS datetime2 FROM airQualityData\n)\nSELECT datetime, data_temp_bme, datetime as \"time\" FROM converted ORDER BY datetime ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}